### PR TITLE
Add gradle and wrapper scripts

### LINKED ISSUE #29: Android project missing gradlew scripts
Project is missing the gradle wrapper scripts (the entrypoint to gradle usage).

### PR DESCRIPTION
**Pull request by AnmAtAnm**
Adding standard gradle and scripts as generated by Android Studio when making a new project.
Including gradle in a project repo (not excluded by default .gitignore) to ensure all
parties are using the same build tool versions.

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #29 🦕

### CODE REVIEW

**Comment by jpoehnelt** [comment]
@AnmAtAnm Please take a moment to fill out [this short survey](https://forms.gle/wYuzN6UibnFj7ZL29). Thank you!

_This is an automated message, feel free to ignore._

**Comment by yuethomas** [comment]
Do these gradle wrapper scripts work when we don't have the gradlew jar checked in?

**Comment by AnmAtAnm** [comment]
I thought the scripts were sufficient, but testing proved this not true.  I've modified this PR to include the gradle binary from a new Android Studio project.

**Comment by AnmAtAnm** [comment]
Bumped to latest gradle 7.4.2

**Pull request merged**
